images/Makefile
pdf should be rebuilt if fsm.dot changes.
=> Make fsm.pdf depend on fsm.dot

docs/design/StratisSoftwareDesign.lyx
Incorporate feedback from the team.
fixes #15
=> Update SWDD to 0.6

Makefile, docs/dbus/DBusAPIReference.lyx, docs/dbus/Makefile
=> Introduce Stratisd D-Bus API Manual.

docs/design/StratisSoftwareDesign.lyx, docs/design/layers.svg
=> Some edits to Section 10.2.6

docs/design/StratisSoftwareDesign.lyx
Hi, here's a take on documenting and standardizing our dm names. GitHub isn't great for reviewing changes to LyX docs... let me know if this works or if you'd prefer I just apply draft text and then review a pdf.
=> Add section on device-mapper naming

docs/design/StratisSoftwareDesign.lyx
Part 3 is Implementation, and that's where Implementation Details
should go.
fixes #35
=> Implementation Details should be in part 3 not part 4

docs/dbus/DBusAPIReference.lyx
It was added to the stratisd D-Bus API in a recent commit.
=> Update filesystem API to include Devnode

docs/dbus/DBusAPIReference.lyx
Both properties have recently been added.
https://github.com/stratis-storage/stratisd/pull/462
=> Document TotalPhysicalSize and TotalPhysicalUsed

docs/design/StratisSoftwareDesign.lyx
This PR addresses a number of design doc issues that have accumulated.
=> Design Doc Updates

docs/style/StratisStyleGuidelines.lyx
=> styledoc: devicemapper use decls get their own section

docs/dbus/DBusAPIReference.lyx
Still need to work on blockdev states.
=> Update apiref for blockdevs

docs/design/StratisSoftwareDesign.lyx
=> Small fixes

docs/dbus/DBusAPIReference.lyx
They have already been removed from stratisd.
Resolves: #69.
=> Remove mention of properties representing constants

docs/dbus/DBusAPIReference.lyx
Signed-off-by: Todd Gill <tgill@redhat.com>
=> Add SnapshotFilesystem description for the pool interface

.gitignore, docs/design/StratisSoftwareDesign.lyx, docs/design/references.bib
=> Add a References section to Stratis design doc

docs/style/StratisStyleGuidelines.lyx
=> Group remarks about use declarations together

docs/design/StratisSoftwareDesign.lyx
=> Update for optional addition of 'private' to DM names

docs/design/StratisSoftwareDesign.lyx
=> design: Rewrite "OS Integration: udev" section a bit

docs/faq/FAQ.md
Added some content for  https://github.com/stratis-storage/stratis-docs/issues/101
Signed-off-by: Tony Asleson <tasleson@redhat.com>
=> Add more entries

docs/dbus/DBusAPIReference.lyx
fix issues from #102 and #95, and do some other light housekeeping.
=> Fix api doc

.gitignore, Makefile, docs/relnotes/Makefile, docs/relnotes/relnotes-1.0.md, website/index.html
Add release notes and update main page.
=> Update website for 1.0 release

docs/faq/FAQ.md
Rearrange to read in a more natural order.
fixes #101
=> Add additional FAQ entries

content/static/FAQ.md
In line with: https://github.com/stratis-storage/stratis-storage.github.io/pull/4
=> this change is in line with PR submitted

Makefile
So pdfs can be made w/out building the whole website.
=> Make new pdfs target

content/relnotes-stratisd-1.0.6.md
=> Release notes for stratisd 1.0.6

docs/design/StratisSoftwareDesign.lyx
=> Add some remarks about encryption in the data tier section

docs/dbus/DBusAPIReference.lyx
Related: https://github.com/stratis-storage/project/issues/51.
=> Idempotency and CreatePool edits

content/2019-11-06.md
Resolves: https://github.com/stratis-storage/project/issues/98.
Supercedes: #137.
=> Add release notes for new version of Stratis

docs/design/StratisSoftwareDesign.lyx
=> Update docs with DBus policy information

docs/design/StratisSoftwareDesign.lyx
=> Fix unterminated sentence that describes the cache tier

docs/dbus/DBusAPIReference.lyx
=> Fix error in docs for versioning of interfaces

docs/dbus/DBusAPIReference.lyx, docs/design/StratisSoftwareDesign.lyx
=> Remove author field from design and dbus docs

README.md
=> Fix up README file

docs/design/StratisSoftwareDesign.lyx
=> Distinguish between KEK and passphrase

docs/design/StratisSoftwareDesign.lyx
=> Encryption implementation appendix

docs/dbus/DBusAPIReference.lyx, docs/design/StratisSoftwareDesign.lyx
=> Update documentation for Report interface

docs/dbus/DBusAPIReference.lyx
=> Documentation for encryption API

content/static/FAQ.md
Supercedes https://github.com/stratis-storage/stratis-storage.github.io/pull/16
=> Fix a typo

content/static/howto.md
=> Update howto page with init-cache/add-cache changes

content/stratis-release-notes-2.3.0.md
=> Release notes for 2.3.0

docs/dbus/DBusAPIReference.lyx
=> Update for version 2.3.0

content/multi-threading.md
=> Multi-threading blog post

content/cryptsetup.md, content/katacoda-tutorial.md, content/multi-threading.md, content/stratis-cli-release-notes-1.1.0.md, content/stratis-cli-release-notes-2.0.1.md, content/stratis-cli-release-notes-2.1.1.md, content/stratis-release-notes-2.0.0.md, content/stratis-release-notes-2.1.0.md, content/stratis-release-notes-2.2.0.md, content/stratis-release-notes-2.2.1.md, content/stratis-release-notes-2.3.0.md, content/stratisd-release-notes-1.0.6.md, content/stratisd-release-notes-2.0.1.md
=> Add author information to blog entries

docs/dbus/DBusAPIReference.lyx
Related to stratis-storage/stratisd#2474
=> Update documentation to mention carrying forward unchanged interfaces

content/stratis-rootfs.md
=> Add Stratis root filesystem blog post

Makefile
Closes https://github.com/stratis-storage/project/issues/292
=> Add new target to make new commit in website repo

content/stratis-release-notes-2.4.1.md
=> Release notes for 2.4.1

content/stratisd-rootfs-packaging.md
=> Note about packaging

content/stratis-release-announce-3.0.0.md
=> Add 3.0 release announcement

content/stratis-release-notes-3.0.0.md
=> Release notes for Stratis 3.0.0

content/stratis-intro.md
=> Include introduction to Stratis

config.toml, content/static/users.md
=> Add list of users and OS's that support Stratis

docs/design/StratisSoftwareDesign.lyx
=> Include mention of hyphenated format for JSON

docs/design/StratisSoftwareDesign.lyx
=> Fully document use of CRC-32C algorithm for checksum

content/per-pool-locking.md
=> Per-pool locking blog post

content/thin-provisioning-redesign.md, docs/design/StratisSoftwareDesign.lyx
@mulkieran It looks like most of the documentation is in alignment with what we want. My only question is whether we want to add information about starting and stopping pools or not.
Closes #272
=> Update design document for 3.1

docs/dbus/blockdev.xml, docs/dbus/filesystem.xml, docs/dbus/manager.xml, docs/dbus/pool.xml
=> Update introspection data

docs/design/StratisSoftwareDesign.lyx
Related to stratis-storage/stratisd#3035
=> Add section highlighting grow physical design

content/stratis-release-notes-3.3.0.md
Related https://github.com/stratis-storage/project/issues/517
=> Release notes for Stratis 3.3.0

docs/dbus/blockdev.xml, docs/dbus/filesystem.xml, docs/dbus/manager.xml, docs/dbus/pool.xml
Related https://github.com/stratis-storage/project/issues/517
=> Update blockdev.xml with r3 interface

content/stratis-release-notes-3.3.0.md
Related github.com/stratis-storage/project/issues/517
=> Fix a few infelicities in release notes

.github/workflows/main.yml, .github/workflows/weekly.yml
=> Install zola from source in CI

.github/workflows/main.yml, .github/workflows/weekly.yml
Related https://github.com/stratis-storage/project/issues/545
=> github actions: update recommended Rust to 1.65

docs/design/StratisSoftwareDesign.lyx
Related https://github.com/stratis-storage/project/issues/372
=> Add consistent block sizes information to design doc

docs/design/StratisSoftwareDesign.lyx
Related to stratis-storage/stratisd#3079
=> Update LUKS2 information for starting pools by name

content/stratis-release-notes-3.4.0.md
Related https://github.com/stratis-storage/project/issues/538
=> Release notes for Stratis 3.4.0

docs/design/StratisSoftwareDesign.lyx
=> Revert "designdoc: Sans Serif font"

.github/workflows/main.yml, .github/workflows/weekly.yml
Related: stratis-storage/project#561
=> github actions: update recommended Rust to 1.66

.github/workflows/main.yml, .github/workflows/weekly.yml
Related: stratis-storage/project#568
=> github actions: update recommended Rust to 1.66.1

.github/workflows/main.yml, .github/workflows/weekly.yml
Related: stratis-storage/project#572
=> github actions: update recommended Rust to 1.67.0

content/static/howto.md
=> Remove references to redundancy in how-to doc

.github/workflows/main.yml, .github/workflows/weekly.yml
Related: stratis-storage/project#573
=> github actions: update recommended Rust to 1.67.1

.github/workflows/main.yml, .github/workflows/weekly.yml
Related: stratis-storage/project#587
=> github actions: update recommended Rust to 1.68.0

content/stratisd-release-notes-3.5.2.md
Related https://github.com/stratis-storage/project/issues/590
=> stratisd 3.5.2 release notes

content/stratisd-release-notes-3.5.2.md
Related https://github.com/stratis-storage/project/issues/590
=> Fix formatting errors

content/stratis-rootfs-fedora.md, content/stratis-rootfs.md
Related to stratis-storage/stratisd#3271
=> Steps for Fedora Stratis root filesystem setup

.github/workflows/dummy.yml, .github/workflows/main.yml, .github/workflows/weekly.yml
Related https://github.com/stratis-storage/project/issues/525
=> Change ubuntu-19.04 to ubuntu-latest

docs/dbus/manager.xml
Related https://github.com/stratis-storage/project/issues/615
=> Revise comments about inconsistent encryption info

docs/dbus/pool.xml
=> Include forgotten GrowPhysicalDevice method

content/stratisd-release-notes-3.5.8.md
Related https://github.com/stratis-storage/project/issues/638
=> Add stratisd 3.5.8 release notes

content/stratisd-release-notes-3.6.4.md
Related https://github.com/stratis-storage/project/issues/685
=> Add release notes for stratisd 3.6.4

.github/workflows/main.yml
Related: stratis-storage/project#733
=> github actions: update recommended Rust to 1.82.0

.github/workflows/main.yml
Related: stratis-storage/project#740
=> github actions: update recommended Rust to 1.83.0

.github/workflows/main.yml
Related: stratis-storage/project#747
=> github actions: update recommended Rust to 1.84.0

.github/workflows/main.yml
Related: stratis-storage/project#751
=> github actions: update recommended Rust to 1.84.1

content/metadata-rework.md
Related to stratis-storage/stratisd#3637
=> Blog post for metadata rework

.github/workflows/main.yml
Related: stratis-storage/project#753
=> github actions: update recommended Rust to 1.85

content/stratis-release-notes-3.8.0.md
Related https://github.com/stratis-storage/project/issues/748
=> Add Stratis 3.8.0 release notes

.github/workflows/main.yml
Related: https://github.com/stratis-storage/project/issues/763
=> github actions: update recommended Rust to 1.86
