- images/fsm.dot
The spare disk needs to be initialized based upon the data in the other
disks in the raid.
> Using a spare when degraded requires sync

- docs/design/StratisSoftwareDesign.lyx
If the start-of-blockdev BDA is overwritten, maybe by an accidental dd,
Stratis also writes the BDA to the end of the blockdev. However, since the
MDA is variable-sized (and we need to read the sigblock to know its size)
put the Static Header in the last 8 sectors, and then define the MDA as
occupying the preceding space, length as defined by the MDA size field
in the sig block.
Signed-off-by: Andy Grover agrover@redhat.com
> Document end-of-blockdev BDA reverses order of MDA and Static Header

- docs/design/StratisSoftwareDesign.lyx
This aligns them against the left hand margin, instead of making them be
treated as new paragraphs.
> Formatting changes for tables.

- docs/design/StratisSoftwareDesign.lyx
"in a thin devices" was obviously wrong, and "culminate" is a tricky word
that _usually_ has something to do with a process rather than a static
structure. I think this is better.
> Slight alteration

- docs/style/StratisStyleGuidelines.lyx
Use declarations must now be alphabetical.
Use 'expect()' instead of 'unwrap()'.
Parsing Linux kernel API output may use expect().
> styledoc: Update for alphabetical and expect usage

- docs/design/StratisSoftwareDesign.lyx
That was the original intention, it just was not expressed properly.
> designdoc: Clarify that dm device name unique id is per-role not per-layer

- docs/design/StratisSoftwareDesign.lyx
Also, fix some old references to Metadata Device to the new Metadata
Volume nomenclature.
Finally, tighten up a couple flabby spots.
> designdoc: Add support for spare metadata device

- docs/dbus/DBusAPIReference.lyx
- docs/design/StratisSoftwareDesign.lyx
These two docs were inconsistent. We now call these two blockdev
fields "user_info" (or UserInfo) and "hardware_info"
(or HardwareInfo) in both.
> Update Design doc and D-Bus API for renamed blockdev properties

- docs/design/StratisSoftwareDesign.lyx
Also, call them Signature Block "location" 1 and 2 instead of "copy"
1 and 2, which I think is better. But also make it clear they are
identical.
Give some of the reasoning behind the scheme.
fixes #87
> Clarify handling of unused sectors in the Static Header

- docs/style/StratisStyleGuidelines.lyx
Document conventions around methods named "request", "alloc", "size",
"available", "usable", and "allocated".
fixes #1190
> style: Add Rust storage-related method naming conventions

- docs/design/StratisSoftwareDesign.lyx
Add version fields to sigblock, mda region header, and metadata. The first two fields are part of the struct they are versioning; the last one is stored in the mda region header, in order to not require parsing JSON to get the metadata version.
> Add versions to structs

- docs/design/StratisSoftwareDesign.lyx
- docs/faq/FAQ.md
This is the new location that stratisd uses to maintain symlinks.
fixes #110
> design & FAQ: Replace /dev/stratis mentions with /stratis

- docs/dbus/DBusAPIReference.lyx
Section 4.2 of the DBus API Reference document indicates a method
'AddDevs' that seems to have been replaced by two new methods:
'AddCacheDevs' and 'AddDataDevs' (or rather, AddDevs became
'AddDataDevs', and a new method 'AddCacheDevs' was added).
This change was introduced via commit
3f55d8c34b1a0df50bfbfb00ded85ce4859b8ad5 but the docs didn't seem to
show it. This patch is an attempt to reflect the change.
Signed-off-by: Jose Castillo <jcastillo@redhat.com>
> Fix DBus API Reference documentation regarding AddDevs method

- docs/dbus/DBusAPIReference.lyx
I made one last edit that I caught right after I had already closed and rebased the PR. Please make sure this is correct when reviewing. I realized `HardwareInfo` and `UserInfo` were still listed as `s` instead of `(bs)` as it is implemented in the code. `SetUserInfo` also documented an `id` parameter that was `s` instead of `(bs)`.
I'll merge this first after #145 for documentation and then go onto the other related PRs.
Supersedes #143 
Supersedes #144 
Closes #135 
Closes #136
> Update D-Bus API reference documentation for v2.0

- docs/design/StratisSoftwareDesign.lyx
Closes #138 
Blocked by #139 
This PR is branched off of issue-stratis-docs-139 so these two should be merged one after another with #140 merged before this pull request.
> Document MPLv2 licensing decision in design docs

- docs/dbus/DBusAPIReference.lyx
This PR documents some of the behavior implemented in https://github.com/stratis-storage/stratisd/pull/1876 more fully.
> Add documentation about duplicate device nodes in arguments

- config.toml
- content/katacoda-tutorial.md
The tutorial has seemingly moved from `/stratis` to `/stratis-configure`.
> Update the Red Hat tutorial link

- .gitignore
- Makefile
- config.toml
- docs/dbus/DBusAPIReference.lyx
- docs/dbus/blockdev.xml
- docs/dbus/filesystem.xml
- docs/dbus/manager.xml
- docs/dbus/pool.xml
- themes/hyde/templates/index.html
Start using introspection data to document our D-Bus API. The result of these changes is that the D-Bus API doc will contain no specific information about the individual interfaces. Instead, it will have links to the XML-formatted introspection data which will be posted on the Stratis website and available in the sidebar under the heading "D-Bus Introspection Files:"
Closes #249
Closes #208
> Stratis docs issue 249 html

- content/stratis-rootfs.md
Without the `.service` suffix specified, systemd will assume that the specified unit file is a `.mount` file and will fail as written.
We should update the documentation to specify this for users looking to implement /etc/fstab support.
> Specify .service in /etc/fstab examples

- docs/dbus/blockdev.xml
- docs/dbus/filesystem.xml
- docs/dbus/manager.xml
- docs/dbus/pool.xml
Related https://github.com/stratis-storage/project/issues/538
All r4 interfaces are identical with r3 interfaces except that Manager.r4 changes the two initial arguments to StartPool.
> Update introspection data for Stratis 3.4.0 release

- content/stratis-release-notes-3.5.0.md
Related https://github.com/stratis-storage/project/issues/567
> Stratis 3.5.0 release notes

- content/static/users.md
Added the stratis-cli package url to users/index.html to let users know that the stratis-cli is also available for archlinux.
(pulled across from stratis-storage/stratis-storage.github.io#31)
> Add stratis-cli archlinux package

- content/stratis-release-notes-3.6.0.md
Related https://github.com/stratis-storage/project/issues/673
> Add Stratis 3.6.0 release notes

- content/static/users.md
> Update Arch Linux package URL in users.md

- docs/dbus/blockdev.xml
- docs/dbus/filesystem.xml
- docs/dbus/manager.xml
- docs/dbus/pool.xml
Related https://github.com/stratis-storage/project/issues/673
> Update introspection docs for r6

- content/stratisd-release-notes-3.6.5.md
Related https://github.com/stratis-storage/project/issues/691
> stratisd 3.6.5 release notes

- content/static/howto.md
- content/stratis-release-notes-3.8.1.md
- content/stratis-rootfs.md
> Remove x-systemd.after= component of example fstab entries
